### PR TITLE
Add method to easily spin up doc server

### PR DESCRIPTION
**Pull request by cpuguy83**
This uses dagger to build the website and serve on a local port. Example usage:

```console
$ go -C ./website run .
```

This will, by default, make the server available on port 3000.

I've set this up as a separate module so that dagger dependencies do not interfere with the main module dependencies.

### CODE REVIEW

**Comment by DannyBrito** [comment]
could, we also add this as maybe reference page in the docs-website on how to run it :)

**Comment by sozercan** [comment]
wow this is fancy

+1 to @DannyBrito's comment about adding to https://github.com/Azure/dalec/blob/main/website/README.md

**Review by sozercan — APPROVED** [review]
LGTM. Thanks!

**Comment by cpuguy83** [comment]
Added the readme, also made some minor changes to make the startup a lot cleaner and better use of caching for node modules.

**Pull request merged**
